### ISSUE TITLE
Update GUI for v4.x releases

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/Hack-Test-Win-Installer#1]
The next Hack release will be v4.000.  The GUI for the test installer will need to be updated to reflect this change.  Here is what it currently displays:

![sa10h-image](https://user-images.githubusercontent.com/4249591/38589313-47693fd2-3cf8-11e8-98cc-f7100537d4c4.png)

**Comment by texhex** [comment]
Should be done, waiting for CI run.

**Comment by texhex** [comment]
CI looks good, test run also OK, closing issue.

**Comment by chrissimpkins** [comment]
@texhex thanks Michael! Does this apply to release installer too?

**Comment by texhex** [comment]
Somewhat. This text (Font release) comes from src\data.ini, so when you are ready with v4 for prime time, I will update the data.ini for the release installer and it will show the current version (most likely v4.000).

**Comment by chrissimpkins** [comment]
@texhex sounds good! ty!

**Comment by texhex** [comment]
@chrissimpkins You're welcome!
